### ISSUE TITLE
IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)

### ISSUE THREAD

**Issue by ChitoseSana6** [AlexandaJerry/whisper-vits-japanese#16]
colab上torch版本1.12.1依旧报错
IndexError: Caught IndexError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/mnt/d/work/whisper-vits-japanese/env/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/mnt/d/work/whisper-vits-japanese/env/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 54, in fetch
    return self.collate_fn(data)
  File "/mnt/d/work/whisper-vits-japanese/data_utils.py", line 121, in __call__
    print([x[1].size(1) for x in batch])
  File "/mnt/d/work/whisper-vits-japanese/data_utils.py", line 121, in <listcomp>
    print([x[1].size(1) for x in batch])
IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)
未对原代码做任何修改

**Comment by AlexandaJerry** [comment]
print([x[1].size(1) for x in batch]) 我看了data_utils.py 121没有写print啊 第121明明是个排序

使用新的代码然后先用isla数据集跑一遍看看，如果isla数据集没问题的话，应该就是有音频转频谱的时候出问题了
